"""Render the LangGraph SOC pipeline contract as Mermaid.

The diagram is generated from `pipeline_contract()` so docs stay aligned with
the runnable graph topology, route conditions, skill ownership, and guardrails.

Run:

    python examples/agents/render_langgraph_pipeline_diagram.py \
      --output docs/diagrams/langgraph-agent-harness.mmd
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from langgraph_security_graph import pipeline_contract

NODE_IDS = {
    "ingest": "ING",
    "normalize": "NORM",
    "enrich": "ENR",
    "correlate": "COR",
    "confidence": "CONF",
    "map": "MAP",
    "llm_triage": "TRIAGE",
    "review": "REVIEW",
    "remediate": "REM",
    "retry_queue": "RETRY",
    "escalate": "ESC",
    "writeback": "AUDIT",
}

LANES = [
    (
        "FACTS",
        "Deterministic skill nodes: evidence and security facts",
        ["ingest", "normalize", "enrich", "correlate", "confidence", "map"],
        "fact",
    ),
    (
        "LLM",
        "Optional model node: bounded triage only",
        ["llm_triage"],
        "agent",
    ),
    (
        "GOV",
        "Governance nodes: approval, dry-run, retry, escalation, audit",
        ["review", "remediate", "retry_queue", "escalate", "writeback"],
        "gate",
    ),
]

CONDITION_LABELS = {
    "always": "",
    "route_after_review == remediate": "approved",
    "route_after_review == writeback": "blocked",
    "route_after_remediation == retry_queue": "retryable API error",
    "route_after_remediation == escalate": "terminal API error",
    "route_after_remediation == writeback": "dry-run OK",
}


def _safe_label(value: str) -> str:
    return value.replace("&", "and").replace('"', "'")


def _join_short(values: list[str], *, limit: int = 2) -> str:
    if not values:
        return "none"
    selected = values[:limit]
    suffix = "" if len(values) <= limit else f" +{len(values) - limit}"
    return " · ".join(selected) + suffix


def _node_label(node: dict[str, Any]) -> str:
    title = node["node"].replace("_", " ")
    skills = _join_short(node.get("skills", []))
    guards = _join_short(node.get("guardrails", []))
    return _safe_label(
        f"{title}<br/>agent: {node['agent_id']}<br/>skills: {skills}<br/>guards: {guards}"
    )


def _edge_line(edge: dict[str, str]) -> str:
    source = NODE_IDS[edge["source"]]
    target = NODE_IDS[edge["target"]]
    label = CONDITION_LABELS[edge["condition"]]
    if label:
        return f"    {source} -- {label} --> {target}"
    return f"    {source} --> {target}"


def render_mermaid() -> str:
    contract = pipeline_contract()
    nodes = {node["node"]: node for node in contract["nodes"]}
    lines = [
        "%% Generated by examples/agents/render_langgraph_pipeline_diagram.py.",
        "%% Source of truth: pipeline_contract() in examples/agents/langgraph_security_graph.py.",
        "%% Do not hand-edit topology here; update the contract and rerun the renderer.",
        "",
        "flowchart LR",
        "    classDef fact fill:#052e2b,stroke:#34d399,color:#ecfdf5",
        "    classDef agent fill:#0b1830,stroke:#60a5fa,color:#dbeafe",
        "    classDef gate fill:#3b2403,stroke:#f59e0b,color:#fef3c7",
        "    classDef write fill:#4c0519,stroke:#fb7185,color:#fff1f2",
        "    classDef audit fill:#1f2937,stroke:#94a3b8,color:#f8fafc",
        "",
    ]
    for lane_id, lane_title, lane_nodes, class_name in LANES:
        lines.append(f'    subgraph {lane_id}["{lane_title}"]')
        for node_name in lane_nodes:
            node_id = NODE_IDS[node_name]
            node = nodes[node_name]
            node_class = class_name
            if node_name == "remediate":
                node_class = "write"
            elif node_name == "writeback":
                node_class = "audit"
            lines.append(f'        {node_id}["{_node_label(node)}"]:::{node_class}')
        lines.append("    end")
        lines.append("")

    lines.extend(_edge_line(edge) for edge in contract["edges"])
    lines.extend(
        [
            "",
            '    RAILS["Non-bypassable rails<br/>allowlist intersection · HITL · dry-run · audit/eval · idempotency"]:::audit',
            "    RAILS -. constrains tool calls .-> ING",
            "    RAILS -. bounds model authority .-> TRIAGE",
            "    RAILS -. gates write paths .-> REM",
            "",
        ]
    )
    return "\n".join(lines).rstrip()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="Write Mermaid to this file instead of stdout.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    rendered = render_mermaid()
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered + "\n", encoding="utf-8")
    else:
        print(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
