{{- if and .Values.volumes.audit.enabled .Values.volumes.audit.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mcp-sse.fullname" . }}-audit
  labels: {{- include "mcp-sse.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.volumes.audit.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.volumes.audit.size }}
{{- end }}
