apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-sse.fullname" . }}
  labels: {{- include "mcp-sse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "mcp-sse.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
